### ISSUE TITLE
Fails to build 'web' service

### ISSUE THREAD

**Issue by xtydsouza** [avenirer/CodeIgniter4-Docker-Apache-PHP-MySQL#2]
I got the following error message while attempting to compose from your zipped [file](https://github.com/avenirer/CodeIgniter4-Docker-Apache-PHP-MySQL)
Step 13/17 : COPY src/ /var/www/html/
ERROR: Service 'web' failed to build : COPY failed: file not found in build context or excluded by .dockerignore: stat src/: file does not exist.
Any idea?
Chris

**Comment by avenirer** [comment]
Hello.

This is the support code for a tutorial I've made here: https://avenir.ro/codeigniter-4-using-docker-apache-mysql/

You can also create the directories "src" and "public" in the root of the project and it should work

**Comment by xtydsouza** [comment]
Thanks Avenirer. I got it running.
Had to mount the public folder too to fix another error while running the web service
- ./public:/var/www/html/public
